## adjust geometry
# max is 1.5 mm
/tablet/thickness 1.5 mm
/hpge/distance 0 mm
/tablet/xpos 0 mm


/run/reinitializeGeometry
/run/initialize
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes -10 -10 -10 10 cm
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
# /gun/particle proton