# to use /control/execute ../macros/prova02.mac
/run/numberOfThreads 1
/tablet/thickness 1.5 mm
/hpge/distance 0 mm
/tablet/xpos 0 mm
/run/reinitializeGeometry

/run/initialize
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 6.5 mm
/gps/energy 100 keV
/gps/ang/type iso
# /gps/direction 0 0 -1 # !!! fixed direction !!!
/gps/pos/centre 0 0 1.5 mm
/run/printProgress 10000
/run/beamOn 10000